src/objects/Area__c.object
<CustomObject>
    <fields>
        <fullName>Assigned_MR__c</fullName>
        <label>Assigned MR</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Areas</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Head_Quarter__c</fullName>
        <label>Head Quarter</label>
        <referenceTo>Head_Quarter__c</referenceTo>
        <relationshipLabel>Areas</relationshipLabel>
        <relationshipName>Areas</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Area</label>
    <nameField>
        <label>Area Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Areas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

MSN-test.md/MSN Backup10032015/src/objects/Head_Quarter__c.object
<CustomObject>
    <fields>
        <fullName>Assigned_MR__c</fullName>
        <label>Assigned MR</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Head_Quarters</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Head Quarter</label>
    <nameField>
        <label>Head Quarter Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Head Quarters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

MSN-test.md/MSN Backup10032015/src/classes/listpageforAreascls.cls
public with sharing class listpageforAreascls {

    public PageReference insertrecord() {
    
    PageReference  ref=new PageReference ('/a0B/e?retURL=%2Fapex%2FlistpageforAreas');
    ref.setredirect(true);
    
        return ref;
    }


    public String searchvalue { get; set; }

public string recid{get;set;}

    public PageReference decrec() {
    
    list<Area__c>lstdel=[select id,Name from Area__c where id=:recid];
    
    delete lstdel;
  
    PageReference ref=new PageReference ('/apex/listpageforAreas?save_new=1&sfdc.override=1');
    ref.setredirect(true);
    
    
        return ref;
    }


    public list<Area__c> lstvalue { get; set; }
    
    public listpageforAreascls ()
    {
    
    String usrProfileName = [select u.Profile.Name from User u where u.id = :Userinfo.getUserId()].Profile.Name;
    
    if(usrProfileName == 'System Administrator'){
    
        lstvalue =[select id,Name,Assigned_MR__c,Head_Quarter__c from Area__c];
    
    }
    
    else if(usrProfileName == 'Medical Representative'){
    
        lstvalue =[select id,Name,Assigned_MR__c,Head_Quarter__c from Area__c where Assigned_MR__c =: Userinfo.getUserId()];
    
    }
    
    }
    
}