src/objects/Area__c.object
<CustomObject>
    <fields>
        <fullName>Assigned_MR__c</fullName>
        <label>Assigned MR</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Areas</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Head_Quarter__c</fullName>
        <label>Head Quarter</label>
        <referenceTo>Head_Quarter__c</referenceTo>
        <relationshipLabel>Areas</relationshipLabel>
        <relationshipName>Areas</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Area</label>
    <nameField>
        <label>Area Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Areas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Chemist__c.object
<CustomObject>
    <fields>
        <fullName>Area_Place__c</fullName>
        <label>Area/Place</label>
        <referenceTo>Area__c</referenceTo>
        <relationshipName>Chemists</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Head_Quarter__c</fullName>
        <label>Head Quarter</label>
        <referenceTo>Head_Quarter__c</referenceTo>
        <relationshipName>Chemists</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MR__c</fullName>
        <label>MR</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Chemists</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Name_of_the_Owner__c</fullName>
        <label>Name of the Owner</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phone__c</fullName>
        <label>Phone</label>
        <type>Phone</type>
    </fields>
    <label>Pharmacist</label>
    <nameField>
        <label>Pharmacist Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pharmacists</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Doctor__c.object
<CustomObject>
    <fields>
        <fullName>Area_Place__c</fullName>
        <label>Area / Place</label>
        <referenceTo>Area__c</referenceTo>
        <relationshipLabel>Doctors</relationshipLabel>
        <relationshipName>Doctors</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Assigned_MR__c</fullName>
        <label>Assigned MR</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Doctors</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <picklist>
            <picklistValues>
                <fullName>VIP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>A</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>B</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Head_Quarter__c</fullName>
        <label>Head Quarter</label>
        <referenceTo>Head_Quarter__c</referenceTo>
        <relationshipLabel>Doctors</relationshipLabel>
        <relationshipName>Doctors</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Hospital__c</fullName>
        <label>Hospital</label>
        <referenceTo>Hospital__c</referenceTo>
        <relationshipLabel>Doctors</relationshipLabel>
        <relationshipName>Doctors</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Phone__c</fullName>
        <label>Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Qualification__c</fullName>
        <label>Qualification</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Speciality__c</fullName>
        <label>Speciality</label>
        <picklist>
            <picklistValues>
                <fullName>Cardio</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CEP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chest Phy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CMO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ENDO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ENT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NEPHRO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NEURO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ORTHO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PEAD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PEAD CARD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RHEUMATO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>URO</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Doctor</label>
    <nameField>
        <label>Doctor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Doctors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

MSN-test.md/MSN Backup10032015/src/objects/Head_Quarter__c.object
<CustomObject>
    <fields>
        <fullName>Assigned_MR__c</fullName>
        <label>Assigned MR</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Head_Quarters</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Head Quarter</label>
    <nameField>
        <label>Head Quarter Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Head Quarters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

MSN-test.md/MSN Backup10032015/src/objects/Hospital__c.object
<CustomObject>
    <fields>
        <fullName>Area__c</fullName>
        <label>Area</label>
        <referenceTo>Area__c</referenceTo>
        <relationshipLabel>Hospitals</relationshipLabel>
        <relationshipName>Hospitals</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Hospital</label>
    <nameField>
        <label>Hospital Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Hospitals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

MSN-test.md/MSN Backup10032015/src/classes/AreaDetailPageControllor.cls
public with sharing class AreaDetailPageControllor {

    public AreaDetailPageControllor(ApexPages.StandardSetController controller) {

    }

Public Area__c Area {get;set;}
public List<Doctor__c > Doctors {get;set;}
public List<Chemist__c  > Pharmacists {get;set;}
public List<Hospital__c > Hospitals {get;set;}


Public id areaId {get;set;}

    public AreaDetailPageControllor(ApexPages.StandardController controller) {
        areaId = ApexPages.Currentpage().getParameters().get('id');
        area = new Area__c();
        area = [select id,name from area__c where id =:areaId ];
        String usrProfileName = [select u.Profile.Name from User u where u.id = :Userinfo.getUserId()].Profile.Name;
       
        
        system.debug('--------------usrProfileName -------------------'+usrProfileName );
        system.debug('--------------Userinfo.getUserId()-------------------'+Userinfo.getUserId());
        
     
        Area = [Select id,Name From Area__c Where id =: areaId];
        Doctors = new List<Doctor__c >();
        Pharmacists = new List<Chemist__c >();
        Hospitals = new List<Hospital__c >();
       
      
     
            Doctors = [Select id,name,Assigned_MR__c,Area_Place__c,Category__c,Speciality__c,Qualification__c,Hospital__c From Doctor__c Where Area_Place__c =: areaId ];
            Pharmacists = [Select id,name,MR__c,Name_of_the_Owner__c,Head_Quarter__c,Area_Place__c,Phone__c From Chemist__c Where Area_place__C =: areaId];
        
       
        

    }

}