src/objects/Brand_Wise_Products_Available__c.object
<CustomObject>
    <fields>
        <fullName>Chemist__c</fullName>
        <label>Chemist</label>
        <referenceTo>Chemist__c</referenceTo>
        <relationshipName>Products_Available</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product_Details__c</fullName>
        <label>Product Details</label>
        <referenceTo>MSN_Product__c</referenceTo>
        <relationshipLabel>Brand Wise Products Available</relationshipLabel>
        <relationshipName>Brand_Wise_Products_Available</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Quantity_Brand_wise__c</fullName>
        <label>Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Brand Wise Products Available</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>Products Available Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Brand Wise Products Available</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Chemist__c.object
<CustomObject>
    <label>Pharmacist</label>
    <nameField>
        <label>Pharmacist Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pharmacists</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/pharmaExt.cls
public with sharing class pharmaExt {

    public Id phId{get;set;}
    public List<Brand_Wise_Products_Available__c> bwpalist{set;get;}
    public Chemist__c PharmacistList{get;set;}
    
        public pharmaExt(ApexPages.StandardController controller) {
        
        phId = ApexPages.Currentpage().getParameters().get('id');
        
       PharmacistList = new Chemist__c ();
       PharmacistList = [Select id,Name From Chemist__c where id =: phId ];
        bwpalist = new List<Brand_Wise_Products_Available__c>();
        bwpalist = [select id,Name,Chemist__c,Product_Details__c,Quantity_Brand_wise__c from Brand_Wise_Products_Available__c where Chemist__c =: phId];
    
        }

}