src/objects/Country__c.object
<CustomObject>
    <label>Country</label>
    <nameField>
        <label>Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

MSN-test.md/MSN Backup10032015/src/objects/Head_Quarter__c.object
<CustomObject>
    <fields>
        <fullName>Assigned_MR__c</fullName>
        <label>Assigned MR</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Head_Quarters</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <referenceTo>Country__c</referenceTo>
        <relationshipLabel>Head Quarters</relationshipLabel>
        <relationshipName>Head_Quarters</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Head Quarter</label>
    <nameField>
        <label>Head Quarter Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Head Quarters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ListpageHeadQuartercls.cls
public with sharing class ListpageHeadQuartercls {

    public PageReference NewheadQuotes() {
    
    PageReference  ref2=new PageReference ('/a0A/e?retURL=%2Fapex%2FlistpageHeadQuarterspage');
   ref2.setredirect(true);
        return ref2;
    }


public string rechid{get;set;}

    public PageReference delhead() {
    
    list<Head_Quarter__c>hlst=[select id,Name from Head_Quarter__c where id=:rechid];
    delete hlst;
    PageReference ref=new PageReference ('/apex/listpageHeadQuarterspage');
    ref.setredirect(true);
    
    
        return ref;
    }


    public list<Head_Quarter__c> lsthead { get; set; }
    
    public ListpageHeadQuartercls ()
    {
    
    lsthead =[select id,Name,Country__c,Assigned_MR__c from Head_Quarter__c];
    
    
    
    
}
}