src/objects/Doctor__c.object
<CustomObject>
    <fields>
        <fullName>Area_Place__c</fullName>
        <label>Area / Place</label>
        <referenceTo>Area__c</referenceTo>
        <relationshipLabel>Doctors</relationshipLabel>
        <relationshipName>Doctors</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <picklist>
            <picklistValues>
                <fullName>VIP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>A</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>B</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Mobile__c</fullName>
        <label>Mobile</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Speciality__c</fullName>
        <label>Speciality</label>
        <picklist>
            <picklistValues>
                <fullName>Cardio</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CEP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chest Phy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CMO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ENDO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ENT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NEPHRO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NEURO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ORTHO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PEAD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PEAD CARD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RHEUMATO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>URO</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Doctor</label>
    <nameField>
        <label>Doctor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Doctors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/MSN_Product__c.object
<CustomObject>
    <label>MSN Product</label>
    <nameField>
        <label>MSN Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>MSN Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

MSN-test.md/MSN Backup10032015/src/objects/Prescribe_Product__c.object
<CustomObject>
    <fields>
        <fullName>Doctor__c</fullName>
        <label>Doctor</label>
        <referenceTo>Doctor__c</referenceTo>
        <relationshipName>Prescribe_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product_Name__c</fullName>
        <label>Product Name</label>
        <referenceTo>MSN_Product__c</referenceTo>
        <relationshipLabel>Prescribed Doctors</relationshipLabel>
        <relationshipName>Prescribe_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Prescribed Product</label>
    <nameField>
        <displayFormat>Prescribed-{0000}</displayFormat>
        <label>Prescribed Products Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Prescribed Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Promoted_Product__c.object
<CustomObject>
    <fields>
        <fullName>Doctor__c</fullName>
        <label>Doctor</label>
        <referenceTo>Doctor__c</referenceTo>
        <relationshipLabel>Promoted Products</relationshipLabel>
        <relationshipName>Promoted_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product_Name__c</fullName>
        <label>Product Name</label>
        <referenceTo>MSN_Product__c</referenceTo>
        <relationshipLabel>Promoted Doctors</relationshipLabel>
        <relationshipName>Promoted_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Promoted Product</label>
    <nameField>
        <displayFormat>Promoted-{0000}</displayFormat>
        <label>Promoted Product Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Promoted Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Targeted_Product__c.object
<CustomObject>
    <fields>
        <fullName>Doctor__c</fullName>
        <label>Doctor</label>
        <referenceTo>Doctor__c</referenceTo>
        <relationshipLabel>Targeted Products</relationshipLabel>
        <relationshipName>Targeted_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product_Name__c</fullName>
        <label>Product Name</label>
        <referenceTo>MSN_Product__c</referenceTo>
        <relationshipLabel>Targeted Doctors</relationshipLabel>
        <relationshipName>Targeted_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Targeted Product</label>
    <nameField>
        <displayFormat>TP-{0000}</displayFormat>
        <label>Targeted Product Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Targeted Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

MSN-test.md/MSN Backup10032015/src/classes/ProductDetailPage_Controllor.cls
public class ProductDetailPage_Controllor {
public List<Prescribe_Product__c> Prescribed{get;set;}
public List<Promoted_Product__c> Promoted {get;set;}
public List<Targeted_Product__c> Targeted {get;set;}
public id ProductId {get;set;}
Public MSN_Product__c MsnPro {get;set;}
    public ProductDetailPage_Controllor(ApexPages.StandardController controller) {
    

    ProductId  = ApexPages.Currentpage().getParameters().get('id');
      
          
        MsnPro = new MSN_Product__c ();
        MsnPro = [Select id,Name From Msn_Product__c where id =: ProductId];
        
        Prescribed = new List<Prescribe_Product__c>();
        Prescribed = [Select id,Name,Doctor__c,Doctor__r.Area_Place__c,Doctor__r.Speciality__c,Doctor__r.Category__c,Doctor__r.Mobile__c From Prescribe_Product__c Where Product_Name__c=: ProductId ];
        
        Promoted = new List<Promoted_Product__c>();
        Promoted = [Select id,Name,Doctor__c,Doctor__r.Area_Place__c,Doctor__r.Speciality__c,Doctor__r.Category__c,Doctor__r.Mobile__c From Promoted_Product__c Where Product_Name__c=: ProductId ];
        
        Targeted = new List<Targeted_Product__c>();
        Targeted = [Select id,Name,Doctor__c,Doctor__r.Area_Place__c,Doctor__r.Speciality__c,Doctor__r.Category__c,Doctor__r.Mobile__c From Targeted_Product__c Where Product_Name__c=: ProductId ];
        
        Integer attachment = [Select count() from Attachment where ParentId =:ProductId]; 
        Integer Note = [Select count() from Note where ParentId =:ProductId];
        
        Integer NoteAndAttachment = attachment + Note;
        
       
    }

}