src/objects/Doctor__c.object
<CustomObject>
    <fields>
        <fullName>Area_Place__c</fullName>
        <label>Area / Place</label>
        <referenceTo>Area__c</referenceTo>
        <relationshipLabel>Doctors</relationshipLabel>
        <relationshipName>Doctors</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Assigned_MR__c</fullName>
        <label>Assigned MR</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Doctors</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <picklist>
            <picklistValues>
                <fullName>VIP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>A</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>B</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Hospital__c</fullName>
        <label>Hospital</label>
        <referenceTo>Hospital__c</referenceTo>
        <relationshipLabel>Doctors</relationshipLabel>
        <relationshipName>Doctors</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Speciality__c</fullName>
        <label>Speciality</label>
        <picklist>
            <picklistValues>
                <fullName>Cardio</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CEP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chest Phy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CMO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ENDO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ENT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NEPHRO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NEURO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ORTHO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PEAD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PEAD CARD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RHEUMATO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>URO</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Doctor</label>
    <nameField>
        <label>Doctor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Doctors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

MSN-test.md/MSN Backup10032015/src/objects/Hospital__c.object
<CustomObject>
    <label>Hospital</label>
    <nameField>
        <label>Hospital Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Hospitals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

MSN-test.md/MSN Backup10032015/src/classes/Doctorlistpagecls.cls
public with sharing class Doctorlistpagecls {

    public PageReference newDoctor() {
    
    PageReference  ref=new PageReference ('/a09/e?retURL=%2Fapex%2FDoctorlistpageviewpage');
    ref.setredirect(true);
    
    
    
        return ref;
    }


public string recdid{get;set;}

    public PageReference delDoc() {
    
    list<Doctor__c>lstD=[select id from Doctor__c where id=:recdid];
    
    delete lstD;
    
    PageReference  refD=new PageReference ('/apex/Doctorlistpageviewpage');
    refD.setredirect(true);
    
    
    
    
    
        return refD;
    }


    public list<Doctor__c> lstDoc { get; set; }
    
    public Doctorlistpagecls ()
    {
    String usrProfileName = [select u.Profile.Name from User u where u.id = :Userinfo.getUserId()].Profile.Name;
    
    if(usrProfileName == 'System Administrator'){
    
        lstDoc =[select id,Name,Area_Place__c,Category__c,Speciality__c,Hospital__c from Doctor__c];
    
    }
    
    else if(usrProfileName == 'Medical Representative'){
    
       lstDoc =[select id,Name,Area_Place__c,Category__c,Speciality__c,Hospital__c from Doctor__c where Assigned_MR__c =: Userinfo.getUserId()];
        
    
    }
   
    
    
    }
    


}