src/objects/Doctor__c.object
<CustomObject>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <picklist>
            <picklistValues>
                <fullName>VIP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>A</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>B</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Hospital__c</fullName>
        <label>Hospital</label>
        <referenceTo>Hospital__c</referenceTo>
        <relationshipLabel>Doctors</relationshipLabel>
        <relationshipName>Doctors</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Mobile__c</fullName>
        <label>Mobile</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Speciality__c</fullName>
        <label>Speciality</label>
        <picklist>
            <picklistValues>
                <fullName>Cardio</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CEP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chest Phy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CMO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ENDO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ENT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NEPHRO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NEURO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ORTHO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PEAD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PEAD CARD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RHEUMATO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>URO</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Doctor</label>
    <nameField>
        <label>Doctor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Doctors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

MSN-test.md/MSN Backup10032015/src/objects/Hospital__c.object
<CustomObject>
    <label>Hospital</label>
    <nameField>
        <label>Hospital Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Hospitals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

MSN-test.md/MSN Backup10032015/src/classes/hospitalDetailPage_Controllor.cls
public class hospitalDetailPage_Controllor {
public id hospitalId {get;set;}
public List<Doctor__c > Doctors {get;set;}
public hospital__c hos {get;set;}

    public hospitalDetailPage_Controllor(ApexPages.StandardController controller) {
    
        hospitalId = ApexPages.Currentpage().getParameters().get('id');
        hos =  [Select id,Name From hospital__c  Where Id =: hospitalId ];
        Doctors = new List<Doctor__c >();
        Doctors = [Select id,Name,Speciality__c,Category__c,Mobile__c From Doctor__c Where hospital__c =: hospitalId ];

    }

}