src/objects/Doctor__c.object
<CustomObject>
    <label>Doctor</label>
    <nameField>
        <label>Doctor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Doctors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/MSN_Product__c.object
<CustomObject>
    <fields>
        <fullName>Price__c</fullName>
        <label>Price</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Product_Code__c</fullName>
        <label>Product Code</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>UOM__c</fullName>
        <label>UOM</label>
        <picklist>
            <picklistValues>
                <fullName>Grams</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Milligrams</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>MSN Product</label>
    <nameField>
        <label>MSN Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>MSN Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

MSN-test.md/MSN Backup10032015/src/objects/Prescribe_Product__c.object
<CustomObject>
    <fields>
        <fullName>Doctor__c</fullName>
        <label>Doctor</label>
        <referenceTo>Doctor__c</referenceTo>
        <relationshipName>Prescribe_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product_Name__c</fullName>
        <label>Product Name</label>
        <referenceTo>MSN_Product__c</referenceTo>
        <relationshipLabel>Prescribed Doctors</relationshipLabel>
        <relationshipName>Prescribe_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Prescribed Product</label>
    <nameField>
        <displayFormat>Prescribed-{0000}</displayFormat>
        <label>Prescribed Products Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Prescribed Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Promoted_Product__c.object
<CustomObject>
    <fields>
        <fullName>Doctor__c</fullName>
        <label>Doctor</label>
        <referenceTo>Doctor__c</referenceTo>
        <relationshipLabel>Promoted Products</relationshipLabel>
        <relationshipName>Promoted_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product_Name__c</fullName>
        <label>Product Name</label>
        <referenceTo>MSN_Product__c</referenceTo>
        <relationshipLabel>Promoted Doctors</relationshipLabel>
        <relationshipName>Promoted_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Promoted Product</label>
    <nameField>
        <displayFormat>Promoted-{0000}</displayFormat>
        <label>Promoted Product Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Promoted Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Targeted_Product__c.object
<CustomObject>
    <fields>
        <fullName>Doctor__c</fullName>
        <label>Doctor</label>
        <referenceTo>Doctor__c</referenceTo>
        <relationshipLabel>Targeted Products</relationshipLabel>
        <relationshipName>Targeted_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product_Name__c</fullName>
        <label>Product Name</label>
        <referenceTo>MSN_Product__c</referenceTo>
        <relationshipLabel>Targeted Doctors</relationshipLabel>
        <relationshipName>Targeted_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Targeted Product</label>
    <nameField>
        <displayFormat>TP-{0000}</displayFormat>
        <label>Targeted Product Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Targeted Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

MSN-test.md/MSN Backup10032015/src/classes/DoctorViewPageExt.cls
public with sharing class DoctorViewPageExt {

    public id docId{get;set;}
    public List<Targeted_Product__c> targetlist{get;set;}
    public List<Prescribe_Product__c> prescribelist{get;set;}
    public List<Promoted_Product__c> promotelist{get;set;}
    public Doctor__c DocList{get;set;}
    public DoctorViewPageExt(ApexPages.StandardController controller) {

    docId = ApexPages.Currentpage().getParameters().get('id');
    
    DocList = new Doctor__c();
    DocList = [select id,name from Doctor__c where id =: docId ];
    
    
    targetlist = new List<Targeted_Product__c>();
    targetlist = [select id,name,doctor__c,Product_Name__c,Product_Name__r.Price__c,Product_Name__r.Product_Code__c,Product_Name__r.UOM__c from Targeted_Product__c where doctor__c =: docId ];
    
     prescribelist = new List<Prescribe_Product__c>();
    prescribelist = [select id,name,doctor__c,Product_Name__c,Product_Name__r.Price__c,Product_Name__r.Product_Code__c,Product_Name__r.UOM__c from Prescribe_Product__c where doctor__c =: docId ];
    
    promotelist = new List<Promoted_Product__c>();
    promotelist = [select id,name,doctor__c,Product_Name__c,Product_Name__r.Price__c,Product_Name__r.Product_Code__c,Product_Name__r.UOM__c from Promoted_Product__c where doctor__c =: docId ];
    }
    

}